session:
  key: CaY5iCkYtN7DqXdiYK1BvmGrQuaSA4Tl4bEk9my0jc0=
admin:
  email: admin@admin.com
  password: admin
database:
  host: 127.0.0.1
  port: 5432
  user: kts_user
  password: kts_pass
  database: kts
bot:
  tg_token: aa
  discussion_timeout: 10
  api_path: https://api.telegram.org/bot
  commands:
    start: start
    stop: stop
    info: info
    add_selection: add_me
    assign: assign
    answer: a


