"""CGK data

Revision ID: 384190f0478e
Revises: c160777ccfdb
Create Date: 2022-09-10 10:00:46.160688

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm, text

from app.quiz.models import AnswerModel, QuestionModel

# revision identifiers, used by Alembic.
revision = '384190f0478e'
down_revision = 'c160777ccfdb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = orm.Session(bind=bind)
    q = "The Trojan War was a battle between which ancient cities?"
    a = "Mycenae & Troy"
    data = [QuestionModel(title=q, answers=[AnswerModel(title=a)])]
    session.add_all(data)
    session.commit()

    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = orm.Session(bind=bind)
    session.execute(text(f"TRUNCATE questions CASCADE"))
    session.execute(text(f"TRUNCATE tg_users CASCADE"))
    session.execute(text(f"TRUNCATE sessions CASCADE"))
    pass
    # ### end Alembic commands ###
