"""CGK data

Revision ID: 384190f0478e
Revises: c160777ccfdb
Create Date: 2022-09-10 10:00:46.160688

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm, text

from app.quiz.models import AnswerModel, QuestionModel

# revision identifiers, used by Alembic.
revision = '384190f0478e'
down_revision = 'c160777ccfdb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = orm.Session(bind=bind)
    session.add_all([
        QuestionModel(title="The Trojan War was a battle between which ancient cities?",
                      answers=[AnswerModel(title="Mycenae & Troy")]),
        QuestionModel(title="How long did the “100 year War” last?",
                      answers=[AnswerModel(title="116 years")]),
        QuestionModel(title="Who was nicknamed Bloody Mary by her opponents?",
                      answers=[AnswerModel(title="Mary I of England")]),
        QuestionModel(title="Name the German-born theoretical physicist?",
                      answers=[AnswerModel(title="Albert Einstein")]),
        QuestionModel(title="In which year did Columbus discover America?",
                      answers=[AnswerModel(title="1492")]),
    ])
    session.commit()

    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = orm.Session(bind=bind)
    session.execute(text(f"TRUNCATE questions CASCADE"))
    session.execute(text(f"TRUNCATE tg_users CASCADE"))
    session.execute(text(f"TRUNCATE sessions CASCADE"))
    pass
    # ### end Alembic commands ###
