"""One user table

Revision ID: 8b565bf1b262
Revises: 384190f0478e
Create Date: 2022-09-12 20:38:32.074460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b565bf1b262'
down_revision = '384190f0478e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tg_user_chat',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['sessions.chat_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id'], ['tg_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id', 'id')
    )
    op.drop_index('ix_tg_chat_users_chat_id', table_name='tg_chat_users')
    op.drop_table('tg_chat_users')
    op.drop_index('ix_last_session_session_id', table_name='last_session')
    op.drop_index('ix_response_stage_session_id', table_name='response_stage')
    op.drop_index('ix_sessions_chat_id', table_name='sessions')
    op.drop_index('ix_sessions_question_session_id', table_name='sessions_question')
    op.drop_index('ix_tg_users_id', table_name='tg_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_tg_users_id', 'tg_users', ['id'], unique=False)
    op.create_index('ix_sessions_question_session_id', 'sessions_question', ['session_id'], unique=False)
    op.create_index('ix_sessions_chat_id', 'sessions', ['chat_id'], unique=False)
    op.create_index('ix_response_stage_session_id', 'response_stage', ['session_id'], unique=False)
    op.create_index('ix_last_session_session_id', 'last_session', ['session_id'], unique=False)
    op.create_table('tg_chat_users',
    sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['sessions.chat_id'], name='tg_chat_users_chat_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id'], ['tg_users.id'], name='tg_chat_users_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id', 'id', name='tg_chat_users_pkey')
    )
    op.create_index('ix_tg_chat_users_chat_id', 'tg_chat_users', ['chat_id'], unique=False)
    op.drop_table('tg_user_chat')
    # ### end Alembic commands ###
