"""CGK

Revision ID: c160777ccfdb
Revises: f4c13cfe2e9d
Create Date: 2022-09-09 21:54:46.867600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c160777ccfdb'
down_revision = 'f4c13cfe2e9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_index(op.f('ix_sessions_chat_id'), 'sessions', ['chat_id'], unique=True)
    op.create_table('tg_users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uname', sa.VARCHAR(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tg_users_id'), 'tg_users', ['id'], unique=False)
    op.create_table('last_session',
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('lead', sa.BigInteger(), nullable=True),
    sa.Column('completed_questions', sa.BigInteger(), nullable=True),
    sa.Column('correct_questions', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['lead'], ['tg_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.chat_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_last_session_session_id'), 'last_session', ['session_id'], unique=False)
    op.create_table('response_stage',
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('respondent', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['respondent'], ['tg_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.chat_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_response_stage_session_id'), 'response_stage', ['session_id'], unique=False)
    op.create_table('sessions_question',
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('started_date', sa.BigInteger(), nullable=False),
    sa.Column('lead', sa.BigInteger(), nullable=True),
    sa.Column('completed_questions', sa.BigInteger(), nullable=True),
    sa.Column('correct_questions', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['lead'], ['tg_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.chat_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_sessions_question_question_id'), 'sessions_question', ['question_id'], unique=False)
    op.create_index(op.f('ix_sessions_question_session_id'), 'sessions_question', ['session_id'], unique=False)
    op.create_table('tg_chat_users',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['sessions.chat_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id'], ['tg_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id', 'id')
    )
    op.create_index(op.f('ix_tg_chat_users_chat_id'), 'tg_chat_users', ['chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tg_chat_users_chat_id'), table_name='tg_chat_users')
    op.drop_table('tg_chat_users')
    op.drop_index(op.f('ix_sessions_question_session_id'), table_name='sessions_question')
    op.drop_index(op.f('ix_sessions_question_question_id'), table_name='sessions_question')
    op.drop_table('sessions_question')
    op.drop_index(op.f('ix_response_stage_session_id'), table_name='response_stage')
    op.drop_table('response_stage')
    op.drop_index(op.f('ix_last_session_session_id'), table_name='last_session')
    op.drop_table('last_session')
    op.drop_index(op.f('ix_tg_users_id'), table_name='tg_users')
    op.drop_table('tg_users')
    op.drop_index(op.f('ix_sessions_chat_id'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
