version: "3.9"
services:
  postgres:
    container_name: db
    image: postgres:latest
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
    environment:
      POSTGRES_DB: "kts"
      POSTGRES_USER: "kts_user"
      POSTGRES_PASSWORD: "kts_pass"
    ports:
      - "5432:5432"
    volumes:
      - /home/user/pg_vol:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U kts_user -d kts" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
  pgadmin:
    container_name: pga
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "secret"
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8880:80"
    volumes:
      - /home/user/pga:/var/lib/pgadmin
  rabbitmq:
    container_name: mq
    image: rabbitmq:3.10-management
    ports:
      - "15672:15672"
      - "5672:5672"
